### ISSUE TITLE
codecov

### ISSUE THREAD

**Issue by h1alexbel** [eo-cqrs/eo-qce#6]

**Comment by 0pdd** [comment]
@h1alexbel 2 puzzles [#10](https://github.com/eo-cqrs/eo-qce/issues/10), [#9](https://github.com/eo-cqrs/eo-qce/issues/9) are still not solved.

**Comment by 0pdd** [comment]
@h1alexbel the puzzle [#10](https://github.com/eo-cqrs/eo-qce/issues/10) is still not solved; solved: [#9](https://github.com/eo-cqrs/eo-qce/issues/9).
